name: Deploy React to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build React app
      run: |
        export NODE_OPTIONS=--openssl-legacy-provider
        npm run build
      
    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        
    - name: Add Host to Known Hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
        
    - name: Deploy to EC2
      run: |
        # Clear existing files and create temp directory
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} '
          sudo rm -rf /usr/share/nginx/html/*
          mkdir -p ~/deploy-temp
        '
        
        # Copy build files
        scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no -r build/* ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:~/deploy-temp/
        
        # Move files to web root and restart nginx
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} '
          sudo cp -r ~/deploy-temp/* /usr/share/nginx/html/
          rm -rf ~/deploy-temp
          sudo systemctl restart nginx
        '

