name: Build & Deploy React to EC2

on:
  push:
    branches:
      - main   

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build React app
        run: npm run build

      - name: Add SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > admin1.pem
          chmod 600 admin1.pem
          
      - name: Deploy to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i admin1.pem -r build/* ec2-user@54.172.166.71:/usr/share/nginx/html/

      
      - name: Restart Nginx
        run: |
          ssh -o StrictHostKeyChecking=no -i admin1.pem ec2-user@54.172.166.71 "sudo systemctl restart nginx"
