name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Install Ansible
        run: pip install ansible
          
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/key.pem
          chmod 400 ~/.ssh/key.pem
          ssh-keyscan ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts
          
      - name: Deploy
        run: |
          cd ansible
          echo "[webservers]" > inventory.ini
          echo "${{ secrets.EC2_IP }} ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/key.pem" >> inventory.ini
          echo "[webservers:vars]" >> inventory.ini
          echo "ansible_python_interpreter=/usr/bin/python3" >> inventory.ini
          ansible-playbook deploy.yml -e "github_user=Ishaan1023"

