name: Deploy React App to Amazon Linux EC2

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build React app
      run: |
        export NODE_OPTIONS=--openssl-legacy-provider
        npm run build

    - name: Setup SSH (write key, perms, known_hosts)
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Verify SSH key and permissions
      run: |
        echo "== List ~/.ssh =="
        ls -l ~/.ssh
        echo
        echo "== Permissions (expect -rw------- for id_rsa) =="
        stat -c "%A %n" ~/.ssh/id_rsa || stat -f "%Sp %N" ~/.ssh/id_rsa
        echo
        echo "== BEGIN/END markers =="
        head -n 2 ~/.ssh/id_rsa
        tail -n 2 ~/.ssh/id_rsa
        echo
        echo "== Fingerprint =="
        ssh-keygen -lf ~/.ssh/id_rsa || true

     - name: Setup SSH key
  run: |
    mkdir -p ~/.ssh
    echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    ssh-keyscan -H <34.227.224.67> >> ~/.ssh/known_hosts
    
    - name: Deploy to Amazon Linux EC2
      run: |
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r build/* ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/usr/share/nginx/html/
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} 'sudo systemctl restart nginx'

